version: '3.1'
services:
  jenkins:
    container_name: jenkins
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - '9080:8080'
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /folder_picsure_machine/:/flyway-configs