version: '3.1'
services:
  jenkins:
    container_name: jenkins
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - '9080:8080'
    volumes:
        - /Users/anilkumardegala/jenkins_home_cic:/var/jenkins_home
        #- /var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /flyway-configs/:/flyway-configs