version: '3.3'
services:   
  migration:
    container_name: migration
    restart: always
    env_file:
      - ${ENV_FILE}
    build: 
      context: .
      dockerfile: DockerFile
    #ports:
      #- "5000:5000"
    networks:
      - public
      
networks:
  public:
      